### ISSUE TITLE
MyQ Lite.....     nullpointerexception: cannot get property 'devicenetworkid' on null object

### ISSUE THREAD

**Issue by NewGuy2021** [brbeaird/SmartThings_MyQ#114]
Hey All.  I'm new to smartapps and ST in general.  I applied brbeaird's MyQ lite smart app to my ST.  When I go into the ST app and enable the smartapp, it has me enter the myq credentials and see's my garage door opener.  Once I click next to finish the setup, it returns with:

There was a problem updating devices:
java.lang.NullPointerException: Cannot get property 'deviceNetworkid' on null object.
Line number: unknown
Last successful step: Sensor Indexing

Any ideas what this could be?  I'm using app version 3.1.4

**Comment by brbeaird** [comment]
I just pushed an update today that may be related to this. Maybe try pulling down that version and trying again?

**Comment by johnposten** [comment]
I'm getting this exact same error.  A few months ago when I tried to get this working I remember getting stopped by this same thing.  I have tried updating to 3.1.5 but yet it still shows 3.1.4 when I open My Q Lite.

**Comment by jjcarey** [comment]
I'm also getting this error. I'm using the latest version v3.1.5

I've followed this post to setup if that helps, https://community.smartthings.com/t/how-to-smartthings-myq-smartapp-using-myq-sensors-with-ifttt/149601

**Comment by brbeaird** [comment]
I take it you do not have sensors on the door? I'll have to play around with it and see if I can reproduce.

**Comment by jjcarey** [comment]
Hey @brbeaird! I got it working and it was my mistake. I didn't have the Door opener Device Handler published properly in Smartthings IDE. Really appropriate your work on this SmartApp!

**Comment by johnposten** [comment]
> I take it you do not have sensors on the door? I'll have to play around with it and see if I can reproduce.

I do have the sensor on my door.

**Comment by brbeaird** [comment]
Version 3.1.4 or 3.1.5 should be fine. This error indicates something did not go right with setting up the door device. After you login to MyQ and select your door, the app tries to create a door device using the device type handler you have installed (depending on whether or not you also selected a sensor to go with the door).

 What do you see when you open the SmartApp under App and Handler versions?

Also, I would be curious what your actual IDE logs show at the time this error happens.

**Comment by johnposten** [comment]
Handlers from ST:
![image](https://user-images.githubusercontent.com/6877416/106675154-d5f14200-6571-11eb-898a-5550376b3d6b.png)

ST Smartapps (I originally installed this from the community installer, and have tried to uninstall/reinstall via community installer many times in the past):
![image](https://user-images.githubusercontent.com/6877416/106675255-0afd9480-6572-11eb-8036-00306bb8b9bf.png)

App and Handler version from SmartApp:
![image](https://user-images.githubusercontent.com/6877416/106675286-1ea8fb00-6572-11eb-95a7-c0a19e0a6ebf.png)

Logs from ST:
![image](https://user-images.githubusercontent.com/6877416/106675593-97a85280-6572-11eb-8e07-61f48dde35d4.png)

I'm thinking of uninstalling everything, even Community Installer, and just intalled MyQ Lite manually.

Thanks for your time helping on this!

**Comment by brbeaird** [comment]
That's good info. Based on the log and your handlers screenshots, it looks like you are missing the MyQ Garage Door Opener device type handler. The logs complain that the app can't find the MyQ Garage Door Opener type, and the only one that seems to be installed in your IDE is the no-sensor version.

Community Installer is normally good about installing everything, but it's been awhile, and I can't remember if it has the device types marked as optional and you still have to select which one(s) you want.

**Comment by johnposten** [comment]
I removed the Community Installer, and all virtual switch and related garage door devices from SmartThings IDE.  Then I just tried setting up MyQ_Lite again.  Unfortunately I get the same thing...

It does not detect my sensor, so I choose the option to create separate on/off switches (right?) then I am getting this error again.  Here are logs:
![image](https://user-images.githubusercontent.com/6877416/106806676-7a808c00-6625-11eb-9af7-f37b2617042b.png)

**Comment by johnposten** [comment]
Ok, so I made some progress.  A partially functioning door, but before we get to that I'd like to clarify something:

- Does the 'NoSensor' version just refer to not having a 3rd party sensor?  So for example even though my opener has a sensor (that came with it and works fine in MyQ) I still choose the NoSensor version because I haven't purchased an extra 3rd party sensor?  After reading what you said about what you explain I believe this is correct, but it is still confusing to select a 'No Sensor' version when I do have a sensor.

I was able to get the NoSensor version installed successfully after removing everything and starting from scratch (yes- I had missed the Device handlers in my last attempt, my bad).  However after doing this I would press the button on the Opener and nothing would happen.  I tried several times and verified that the MyQ app was able to control it.

I am able to open the door successfully, but only from the Virtual Tile.
- Virtual Tile works to Open, but doesn't work to Close
- Door Closer switch doesn't work at all
- Door Opener switch doesn't work at all

I've tried getting you logs of these failures to close, but it seems they aren't showing up in the SmartThings IDE.

Any suggestions appreciated.  Thanks!

**Comment by brbeaird** [comment]
> * Does the 'NoSensor' version just refer to not having a 3rd party sensor?

Yes - the sensor would need to be a 3rd party sensor that SmartThings can connect to directly. The MyQ sensor does not count in this case.

Now that I know that, it explains a lot. This SmartApp is quite limited right now if you do not have a separate sensor. The buttons on the device in the mobile app do not work - this is a known limitation of custom device type handlers and the new app.

The momentary opener/closer buttons should work, although I have not tried them in awhile and probably need to dig back into those.

If you don't want to bother with a separate sensor, I would suggest looking into the IFTTT method documented here: https://community.smartthings.com/t/how-to-smartthings-myq-smartapp-using-myq-sensors-with-ifttt/149601

This uses a combination of IFTTT and a virtual sensor to basically "fake" a sensor being on the door so you can use the sensor version of the device handler.

**Comment by johnposten** [comment]
Ahh I didn't realize that.  Thanks for clarifying!

I will try the IFTTT route then, I didn't realize that it could work without the open/close buttons functioning.

Thanks for your work on this!

**Comment by rbarbrow** [comment]
I installed this today and got the save error.


```
Summary
Installation Details:
There was a problem updating devices:
 java.lang.NullPointerException: Cannot get property 'deviceNetworkId' on null object.
Line number: 611
Last successful step: Sensor Indexing
```

**Comment by brbeaird** [comment]
This version is obsolete - Groovy SmartApps no longer work. See the new version here: https://github.com/brbeaird/SmartThings-MyQ-Edge
