### ISSUE TITLE
Issue with tap action

### ISSUE THREAD

**Issue by jsarcone** [brbeaird/SmartThings_MyQ#54]
This has been working fine for a while. I tried updating to 2.1.2 things went bad. The tilt sensor started not to work right. Tried to remove it from the classic application and from the portal but it would not completely be removed. I attempted to install it again and the automation works right but it I tap on the button from the list of devices for the garage door it will not work. I have as a favorite and it give me "unathorized to do this". This did work before going through all this work. Sorry for all the details.

**Comment by jsarcone** [comment]
Thank you so much for the quick response. It odd with the tilt sensor and I agree with you on the your response. I agree with you not needing to touch the device other than rerunning the setup. I do notice when I get to the end of the set it states you're not on 2.1.2 but 2.1.1. However, st-install status says I an on that version. I will try it again. What is the best way unistall completely? I could get that done completely.

**Comment by brbeaird** [comment]
To uninstall completely, you need to go to each door device in the SmartThings app and force-delete it so it gets removed from all automations/SmartApps. Then you can go into MyQ Lite and uninstall. I wish removing the SmartApp would automatically be able to force-delete the doors, but that does not work for whatever reason.

**Comment by brbeaird** [comment]
I actually just pushed a new version that has an auto force-uninstall option. If you'll update the SmartApp code, you can try that out and see if it's any easier for you. I also fixed the issue where the latest version number was not matching up.

**Comment by jsarcone** [comment]
Ok let me try. Thank you so much for your help.

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by jsarcone** [comment]
Ok. I finally got it completely removed. I reinstalled the app and still have the same issue with tapping the button.
So, if I click on the link closed next to device. The is no response and it will not open the door.

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by kc6108** [comment]
Uninstall option didn’t work for me. Maybe due to integration with IFTTT, Alexa, and Google? It didn’t remove a single device handler. Also, if I add momentary titles then redo setup with them it now can’t remove them. Sometimes one, sometimes both, but always at least one. Another thing, community installer doesn’t show the tiles as optional. Also, even if installed, it always shows as not installed.

**Comment by jsarcone** [comment]
Ahh. I think you are right about that. I didn't notice that. I will try installing that manually and seeing if that works.

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by brbeaird** [comment]
Oops, yep I needed to make one more change to actually do "force" deletion in the uninstall piece. Pushed another update that should fix that.

I set the momentary buttons as optional because they're only needed if you choose the option for them, which is really only needed if you're not using a sensor on the door. Still, you may be right that it's just easier to make it all mandatory just for simplicity sake.

As for issues removing those, the latest update also adds more aggressive deletion to that part. See if it works any better now.

**Comment by kc6108** [comment]
The buttons are being removed now when I deselect them.

**Comment by jsarcone** [comment]
I’m able to get everything installed but still having trouble clicking on the icon to open or close door.

**Comment by brbeaird** [comment]
Which icon exactly? What kind of trouble? Is there an error in the IDE logging when you do it?

**Comment by jsarcone** [comment]
If I make it a favorite I get this error. And then on the list of devices nothing happened at all until I go into the device it’s self. And then I can do an open button and close button and that’ll work
![screenshot_20190101-232402_smartthings](https://user-images.githubusercontent.com/23225346/50672780-0f78ad00-0fa8-11e9-9b52-8a5ca2135735.jpg)

**Comment by brbeaird** [comment]
Ok, got this figured out. Just pushed an update to the door device handler that should fix that. Give it a try.

**Comment by jsarcone** [comment]
👍 You got it!!! Thank you so much!
